### ISSUE TITLE
stripObject could be implemented with Array.map

### ISSUE THREAD

**Issue by ZooeyMiller** [fac-12/TeamQ-autocomplete#46]
in `stripObject` you use a forEach, pushing to a new array, as so: 

```
const stripObject = function(allNames) {
  var onlyNamesArr = [];
  allNames.forEach(function(obj){
    onlyNamesArr.push({"name":obj.name});
  })
  return onlyNamesArr;
};
```

This is a perfect use case for the array method [map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map). `Array.map` is a super useful and if you get a chance it's really worth getting to grips with!

**Comment by shannonjensen** [comment]
Ah yes, thank you for the suggestion!
