### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by hannahcmtucker** [fac-12/TeamQ-autocomplete#48]
This is so good guys - love the idea & really well executed :smile:

only one thing from me, I noticed you had a failing test:

<img width="523" alt="screen shot 2017-11-17 at 10 24 34" src="https://user-images.githubusercontent.com/13917339/32942673-a40bbe74-cb81-11e7-9574-2910f65d0530.png">

**Comment by njseeto** [comment]
<img width="888" alt="screen shot 2017-11-17 at 10 31 30" src="https://user-images.githubusercontent.com/29227502/32942969-8515e2b4-cb82-11e7-91e7-c27da0dcf346.png">

Looks like it's a small issue with the order of the array 😄
