### ISSUE TITLE
checkNames could be implemented using `String.startsWith`

### ISSUE THREAD

**Issue by ZooeyMiller** [fac-12/TeamQ-autocomplete#50]
JS has a really nice built in String method for checking if a string starts with another string called [`String.startsWith`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith). This could be useful in your `checkNames` function.

**Comment by shannonjensen** [comment]
Ah very good to know! Thank you!
