### ISSUE TITLE
Front End Relative links

### ISSUE THREAD

**Issue by mineshmshah** [fac-12/TeamQ-autocomplete#51]
When using links in the front end you can use relative links. This is just the way the front end data is compiled. 

So instead of `<script src=".public/script.js"></script>`, you can have `<script src=".public/script.js"></script>`.

Not a huge issue at all, but when using frameworks in the future after week 8 using the relative links can be really handy! 

On a great note the code is incredibly clean and easy to follow! Amazing job!! :)

**Comment by trc5019** [comment]
I think there is a typo in the code because both of them are the same.
