### ISSUE TITLE
Simple Front end validation with CSS

### ISSUE THREAD

**Issue by mineshmshah** [fac-12/TeamQ-autocomplete#54]
I couldnt find myself in the datalist!  *gasp* 

Really amazing concept. Just to make the UI a lot more interactive and to alert the user more on the front end when there is an error, you can simply have some form of a css style to change the border around the search box for example to indicate to the user there are no names matching in the data list.

A popular npm module you could have a look at is called flash and validator to help front end validation more. It deals with alot of popular cases for forms so going forward in the future, especiall when you are introduced to frameworks it can really make your code stand out!

I am so impressed!!

**Comment by shannonjensen** [comment]
Super useful suggestion - thank you! Will look into your recommended modules.

**Comment by shannonjensen** [comment]
Had a hard time finding clear documentation on npm flash module on quick google, but implemented idea in simple way by changing the outline (which is normally blue) to red when no matching names via a class assignment and removal. Doing this also revealed a flaw in our code where the delete key wasn't registering as a keypress so changed to keyup.
