### ISSUE TITLE
sortByPop export

### ISSUE THREAD

**Issue by mineshmshah** [fac-12/TeamQ-autocomplete#55]
In the logic.js file in the backend you are exporting the sortByPop file. It is not being used outside of the file so it doesn't need to be exported. I'd keep it in there if you were using it in your tests (but i believe back end testing is week5).

This is not a bug just cleaning redundant code :)

**Comment by shannonjensen** [comment]
Yes was there for tests but not sure if we actually wrote a test for it in the end!
